name: Generate Metrics Dashboard

on:
   push:
    branches: [ main ]
  workflow_dispatch: {}   # cho phép chạy thủ công từ tab Actions

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
